---
name: skill-engineer
description: Design, test, review, and maintain agent skills using multi-agent iterative refinement. Orchestrates Designer, Reviewer, and Tester subagents for quality-gated skill development. Owns the full lifecycle of skills including validation, testing, and quality assurance.
version: 3.0.0
triggers:
  - design skill
  - create skill
  - review skill
  - test skill
  - audit skills
  - validate skill
  - check skill quality
  - agent kit quality
  - skill lifecycle
  - evaluate skill
  - refactor skill
  - polish skill
  - skill testing
  - skill maintenance
  - skill quality gates
---
